language: cpp
sudo: required

compiler:
    - g++

services:
    - docker

env:
  DOCKER_COMPOSE_VERSION: 1.11.2

addons:
  sonarqube:
    organization: "aferber-github"
    token:
      secure: $SONAR_SECURITY_TOKEN_NEW
    branches:
      - .* 

before_install:
    - docker version
    - docker-compose version
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.9
    - export CXX="g++-4.9"

script:
    - git clone https://github.com/edenhill/librdkafka.git 
    - cd librdkafka
    - ./configure
    - make
    - sudo make install
    - cd ..
    - mkdir /tmp/build
    - cd /tmp/build
    - cmake $TRAVIS_BUILD_DIR
    - export LD_LIBRARY_PATH=/usr/local/lib
    - build-wrapper-linux-x86-64 --out-dir $TRAVIS_BUILD_DIR/bw-output make clean all
    - ./ppm_tests
    - cd $TRAVIS_BUILD_DIR
    - mkdir coverage
    - cd coverage 
    - gcov $TRAVIS_BUILD_DIR/cv-lib/src/*.cpp --object-directory /tmp/build/cv-lib/CMakeFiles/CVLib.dir/src/
    - gcov $TRAVIS_BUILD_DIR/src/*.cpp --object-directory /tmp/build/CMakeFiles/ppm_tests.dir/src/ 
    - cd $TRAVIS_BUILD_DIR
    - sonar-scanner
    #- ./do_kafka_test.sh

cache:
  directories:
    - '$HOME/.sonar/cache'
